name = "smallweb-blog"
main = "worker/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Static Assets configuration for Workers
[assets]
directory = "./dist"
binding = "ASSETS"

# Custom domain
[[routes]]
pattern = "smallweb.blog"
custom_domain = true

[[routes]]
pattern = "www.smallweb.blog"
custom_domain = true
